data:
  path: data/zameen-updated.csv
  target: price
  drop_columns:
    - property_id
    - page_url
    - date_added
    - agency
    - agent

split:
  test_size: 0.2
  random_state: 42

model:
  type: RandomForestRegressor
  params:
    n_estimators: 120
    max_depth: 18
    min_samples_split: 2
    min_samples_leaf: 1
    n_jobs: -1

training:
  shuffle: true
